Bumped to v13.12.1 (#17)
* fix: handle JSON content in run_doc_method

* fix: publish realtime to work with localhost

Currently, Publish realtime does not work in development environment
untill and unless site get's opened with sitename.

Fixed it by using currentsite.txt incase of host is localhost (by
ignoring port).

* fix: cannot read property 'datamanager' of undefined

* refactor: child table filtering

* refactor: child table filtering

* fix: Show user name with workflow state in timeline

(cherry picked from commit 602bfd4b62995d55ac2ab4cf7cbd94613805a923)

* fix: Translate "You" in get_user_link

* fix: allow updating naming series (Backport #13204)

Co-authored-by: Suraj Shetty <13928957+surajshetty3416@users.noreply.github.com>

* fix: Total Row in query report still hidden (backport #14183) (#14191)

Co-authored-by: Shariq Ansari <30859809+shariquerik@users.noreply.github.com>

* fix: Duplicate name columns in list_view when no title field defined (backport #14006) (#14187)

Co-authored-by: Suraj Shetty <13928957+surajshetty3416@users.noreply.github.com>
Co-authored-by: Steve <mcd.steven@gmail.com>

* fix: Show login page instantly

(cherry picked from commit fd264159931aa5b6d8966bb93eb1940b20e09608)

* fix: Update login page & footer style

(cherry picked from commit 7f7ab7647958dad62c2580b2712d3607fc72e292)

* fix: Redirect after login

(cherry picked from commit 8b707278b9946e01ac824d655c312d35592ecb7f)

* test: Add test case for redirection after login

(cherry picked from commit 4c9fd5754fd76175c7a54811d02562a07f1f6462)

* fix: Total Row hidden (#14209)

(cherry picked from commit 95ad6bb4ca2fcfbc3a20643ed437180c06d5dc4e)

* fix: Set DocumentNamingRule.counter as no_copy

(cherry picked from commit 479a583e4b8fa8f09ef43627469cafa2d5b93bf2)

* chore: Drop extra license line

(cherry picked from commit 79cd3ea60e0b526655dc7d294621742ba1b3cfd5)

# Conflicts:
#	frappe/core/doctype/version/version.py

* fix: Don't need postgres to use Frappe

* Made code DRY-er by using obscure frappe.db.is_data_too_long
* Python would run psycopg import line which would check if postgres is
  installed. Sites just wanting to chill w MariaDB would also need
  Postgres to be installed to get Frappe running. Fixes https://github.com/frappe/frappe/issues/14193

(cherry picked from commit 1545ad65d1ba8519b9064c78275d075350f496b9)

* refactor: Use Query Builder instead of raw queries

(cherry picked from commit 53f92e5b5cb59d7955bdbb5afa00e327f6a75eec)

* fix: Invalid translation string

(cherry picked from commit f1c29a16eb9eda78d300f1d1b259e2ec6ec0e0de)

# Conflicts:
#	frappe/utils/password.py

* chore: Raise NotImplementedError in base Database class

Methods that have to be overridden should throw NoteImplementedError.
Helps during development :')

(cherry picked from commit 713eaf6ac98676c84610a9897f65e68e828a0421)

* refactor: Query Builder over Raw SQL

Converted 3 (1 multisql + 2 simple updates) raw queries in frappe.utils.password

(cherry picked from commit fb42d9f68c776cfb3353f03f10a1a7ae8acce6b6)

* fix: Merge conflicts from backport

* fix(translation): Set translated text as html to get unescaped output

(cherry picked from commit 268d344f1a5b544ae4daba539147a170065d1299)

* fix(UI): Clicking area around file view row opens the file

(cherry picked from commit 90bc9e23174b559fbfac0e3b708fee2e77cd6c53)

* fix: remove unnecessary padding

(cherry picked from commit 1e2287855496576fb373632d6f1879e7c4239123)

* fix: section with collapsible content jerk issue

(cherry picked from commit ae10160e618d9d413c25a5feaadcf3f057cc6dcb)

* fix(grid): date or datetime fields disappearing on save (#14228)

(cherry picked from commit fb508607e0c45dc776a41c2fd661a145a751f9c0)

Co-authored-by: Sagar Vora <sagar@resilient.tech>

* fix(UI): Checkbox hidden in List view in mobile view (#14144)

(cherry picked from commit 3bde63eca26ceddd2832d5f9cf4a4b038855f9e9)

* fix(database): Fixed sql convention inconsistency (#14230)

(cherry picked from commit ac9ab3bd95c8d18f8ec74efc89dd21f4a20cc7a6)

* fix: CSV upload failure

(cherry picked from commit 9a66f185e7729a2f33a2641b1a03cc8bbc8ef7a7)

* fix(grid): Delete all functionality

(cherry picked from commit 47b0117eec3f5e1d6d5fb703cbbb53a26f9ed22e)

* fix: reverse tab navigation

Reverse tab navigation seems to be broken from years, instead of going
back to previous field it jumps to primary button.

Root cause: when all fields are exhausted it's suppose to go to primary
button, however that's not the case for shift-tab.

(cherry picked from commit eafb8f6081deadb32d45f28d23dce3257766bd14)

* fix(Workflow Action): Pass doc to attach_print to avoid "Not Found"
- Printview used to go empty for new document due to "Not Found" error in printview because that new document has not been saved in the database while processing workflow action email.

(cherry picked from commit 20c9af556f6a420198fb44f02f4242f7c2b2fdce)

* fix: Link workflow document

(cherry picked from commit 1553ebdc99675a99c7ffdcf02427c83cd16f31ac)

* fix: update record linking desciption in Note

(cherry picked from commit 1c693a84aa96b3b5bb56d92dd4411ae140c65906)

* feat: Able to use custom port for database load balancers

(cherry picked from commit 85834d7a000759af5526c7b3f93d04b44bf6bc88)

* feat: custom database port for read-only replica configuration

(cherry picked from commit 1ee23859447834f166bc4dbdd05cbd2e7c8e510a)

* fix: Keep checkbox checked after updating checked rows (backport #14110) (#14258)

Co-authored-by: Suraj Shetty <13928957+surajshetty3416@users.noreply.github.com>
Co-authored-by: Shariq Ansari <30859809+shariquerik@users.noreply.github.com>

* fix: Pass no_default_fields parameter further down to recursive calls (backport #14158) (#14200)

(cherry picked from commit 4415351597daf6b6d4b0323ca6ece83c80e12855)

Co-authored-by: Steffen <steffen@brennscheidt.net>

* fix: properly queue tasks in `frappe.model.trigger` (#14263)

(cherry picked from commit 778ab5919c9b1752dccf01ebe513af4a269a69e4)

Co-authored-by: Sagar Vora <sagar@resilient.tech>

* fix: Webform Permission for custom doctype (#13594)

* refactor(minor): Built Assets Management

(cherry picked from commit d8020672b0322ad05a2c776ab124972d9ac3e05a)

# Conflicts:
#	frappe/build.py

* refactor: Show sync option only if mail protocol is imap

* fix: Raise email account missing error if found while sending mail

* fix: Sendmail is failing randomly

This is happening because we enqueue the sendmail task before the
current transaction is commited. enqueued task is looking for a document
that is not yet commited and thus failing to send mails.

* fix: change field type data to small text

* fix: Only system manager is able to create tags

Currently creating tags for a document by any user other than system
manager throwing error. Fixed it by giving permissions to `ALL` role.

(cherry picked from commit e4ef3a40c597c30a6b9874e318e628816fc54b83)

* fix: use decimal digits precision 9 instead of 6 while creating schema

Currently we use DECIMAL(18, 6) datatype for float, currency and
percent. But in the system settings we provide a configuration to change the
precision up to 9 digits. This obviously does not work because we do not
store 9 digit precision in database. Fixed by changing the decimal
datatype scale.

(cherry picked from commit a76445bcf581bdf2ebf4fbdd4f882f83c9c3983f)

* fix: set correct title

* fix(cleanup): cleanup email account, bug fix for web_template.js and more

(cherry picked from commit cec53b595a50afc323942cb39f6414f351369676)

* fix: Reloading doc before Setting Property After Alert (#14048)

* feat: provision to add multiple network printers

(cherry picked from commit ec938c960e6fe3c7d0683953fa4e83c9ff5c352f)

# Conflicts:
#	frappe/printing/doctype/print_settings/print_settings.json

* fix: sider issues

(cherry picked from commit 55bd04f91b2e72799fd843ee1b56f1c5244a2acc)

* fix: removing print statements

(cherry picked from commit be2abdbc56131c555249257d34eccda55c54d1a7)

* review changes

(cherry picked from commit cfe4dc41c007fbf968e11ffe66532609f389cc3e)

# Conflicts:
#	frappe/printing/doctype/print_settings/print_settings.json

* fix: sider issues

(cherry picked from commit 2bd2ee36557780d03086d986e945f372604f47de)

* fix: error message

(cherry picked from commit 3f0df6946e763dc475f394db0b368727a7b00e6b)

* fix: error message

(cherry picked from commit 06667968ab4022801de9a44b08abae3f9f7fa03b)

* fix: sider issue

(cherry picked from commit f10d2251e11988d4353491d41fbead69e6a9eaf0)

* fix: conflict resolved

* fix(Event Streaming): Doctype dependencies sync (#14299)

File "/home/mai/Workspace/V13/v13_online/apps/frappe/frappe/event_streaming/doctype/event_producer/event_producer.py", line 414, in sync_child_table_dependencies
    child_doc = frappe._dict(child_doc)
TypeError: 'NoneType' object is not iterable

(cherry picked from commit 1534e5398af4a8971c754fac2c65f87bb8b898a5)

* fix: include doc details in workflow action email subject

(cherry picked from commit 73843b0ab300f8c90da2fddb54b339fd316718f4)

* fix: number format converting to decimals

(cherry picked from commit 39f504be23c97175231e44cf10b08bb962c3b5fe)

* fix: no need for focusout in favour of onchange

(cherry picked from commit 52941e55b105a64da970de33b7c340422540fbab)

# Conflicts:
#	frappe/public/js/frappe/form/controls/int.js

* test: tests for float control

(cherry picked from commit 9eff8bee21de05ac23e92457353f005ccb2207d1)

* chore: add semi colon

(cherry picked from commit 8aea1254f9023d013fab81bc1f29ce2347a95a7c)

* test: tests for control: float

(cherry picked from commit 9dc8f84aedfe33f8e1de76f58b9089c89b19582d)

* revert: removal of flt on focus event

(cherry picked from commit 21a4331be45ab32a2b6dd12c7d45b5f7d612c60b)

* fix: convert back to number_format on change

(cherry picked from commit f29138d6f853233913bf675655a743f5b642f5ba)

# Conflicts:
#	frappe/public/js/frappe/form/controls/float.js

* fix: make flt value idempotent

(cherry picked from commit 4d0b0d35efa64a1692e075b71ae70c4969b81cda)

* chore: sider

(cherry picked from commit 906c70b2456f681a6afaa7b56ea84695f364f824)

* minor: fix merge conflicts

* minor: merge conflicts

* fix: Get background jobs info

(cherry picked from commit d333b009045b3f881f3cc55d984d1deecb9b1979)

* fix: syntax error in float.js

* fix: Resolve conflicts

* fix: Use capital M in max to avoid libsass compatibility issue

https://github.com/sass/sass/issues/2849
https://github.com/sass/sass/issues/2849#issuecomment-820538086
(cherry picked from commit b389a9023007ed1c1bd865f1fb58d9e6826de84b)

* chore: change log for v13_12_0

* bumped to version 13.12.0

* fix: browser printing broken

(cherry picked from commit 34ba19a131765e8110b6e261f20199e93e2929e5)

* bumped to version 13.12.1

* fix: translations

* fix: remove changelog

* feat: translations

* feat: translations

* fix: video translations

* fix: remove duplicate parent when child item option

* translations

* fix: pagos360

* trans

Co-authored-by: barredterra <14891507+barredterra@users.noreply.github.com>
Co-authored-by: leela <leela.vadlamudi@gmail.com>
Co-authored-by: Saqib Ansari <nextchamp.saqib@gmail.com>
Co-authored-by: Gavin D'souza <gavin18d@gmail.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Co-authored-by: Mohammad Hasnain Mohsin Rajan <hasnain2808@gmail.com>
Co-authored-by: Suraj Shetty <13928957+surajshetty3416@users.noreply.github.com>
Co-authored-by: Shariq Ansari <30859809+shariquerik@users.noreply.github.com>
Co-authored-by: Steve <mcd.steven@gmail.com>
Co-authored-by: Suraj Shetty <surajshetty3416@gmail.com>
Co-authored-by: Shariq Ansari <sharique.rik@gmail.com>
Co-authored-by: Jannat Patel <pateljannat2308@gmail.com>
Co-authored-by: Sagar Vora <sagar@resilient.tech>
Co-authored-by: Samuel Braun <42311986+MindLaborDev@users.noreply.github.com>
Co-authored-by: Ankush Menat <ankush@iwebnotes.com>
Co-authored-by: Kenneth Sequeira <seq.kenneth@gmail.com>
Co-authored-by: lukptr <lukptr@ridhosribumi.com>
Co-authored-by: lukptr <17918335+lukptr@users.noreply.github.com>
Co-authored-by: Steffen <steffen@brennscheidt.net>
Co-authored-by: Leela vadlamudi <leela@users.noreply.github.com>
Co-authored-by: bhavesh95863 <bhavesh.freelancer95863@gmail.com>
Co-authored-by: Rushabh Mehta <rmehta@gmail.com>
Co-authored-by: Anupam <anupamvns0099@gmail.com>
Co-authored-by: Mai Ismail <mai.mq.1995@gmail.com>
Co-authored-by: Rohit Waghchaure <rohitw1991@gmail.com>